name: C Build (MSVC)

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - uses: actions/checkout@v3  # Checkout your code
      - name: Set up MSVC environment
        shell: cmd
        run: |
          choco install visualstudio2022buildtools --no-progress
          choco install visualstudio2022-workload-vctools --no-progress
          for /f "usebackq tokens=*" %%i in (`vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath`) do set VS_PATH=%%i
          "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
      - name: Build the project with MSVC
        run: |
          cl /Zi /DDEBUG folder_mirror.c
      - name: Run the project
        run: |
          .\folder_mirror.exe
