name: C Build (MSVC)

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - uses: actions/checkout@v3  # Checkout your code
      - name: Set up MSVC environment
        shell: cmd
        run: |
          ${{ '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && del .\folder_mirror.exe && cl /Zi /DDEBUG folder_mirror.c && .\folder_mirror.exe' }}
          
          
