name: C Build (MSVC)

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - uses: actions/checkout@v3  # Checkout your code
      - name: Set up MSVC environment
        shell: cmd
        run: |
          dir "C:\Program Files\Microsoft Visual Studio"
          dir "C:\Program Files\Microsoft Visual Studio 14.0"
          dir "C:\Program Files (x86)\Microsoft Visual Studio"
          dir "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
          "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
      - name: Build the project with MSVC
        run: |
          cl /Zi /DDEBUG folder_mirror.c
      - name: Run the project
        run: |
          .\folder_mirror.exe
