name: C Build (MSVC)

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - uses: actions/checkout@v3  # Checkout your code
      - name: Set up MSVC environment
        shell: cmd
        run: |
          choco install visualstudio2022buildtools --no-progress
          choco install visualstudio2022-workload-vctools --no-progress
          dir "C:\Program Files (x86)\Microsoft Visual Studio"
          "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat"
      - name: Build the project with MSVC
        run: |
          cl /Zi /DDEBUG folder_mirror.c
      - name: Run the project
        run: |
          .\folder_mirror.exe
